<a href="https://colab.research.google.com/github/cyberburi/Preprocess-Dataset/blob/master/Data_preprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# First, look at everything.
from subprocess import check_output
print(check_output(["ls", "../content/beer-consumption-sao-paulo.zip"]).decode("utf8"))

../content/beer-consumption-sao-paulo.zip



In [0]:
#  Pick a Dataset you might be interested in.
#  Say, all airline-safety files...
import zipfile

# Will unzip the files so that you can see them..
with zipfile.ZipFile("../content/beer-consumption-sao-paulo.zip","r") as z:
    z.extractall(".")

In [5]:
from subprocess import check_output
print(check_output(["ls", "Consumo_cerveja.csv"]).decode("utf8"))

Consumo_cerveja.csv



In [26]:
# There's only one file above...we'll select it.
d=pd.read_csv("Consumo_cerveja.csv")
d.head(1)
d.shape

(365, 6)

In [27]:
d.isnull().sum

<bound method DataFrame.sum of      Temperatura Media (C)  Temperatura Minima (C)  Temperatura Maxima (C)  \
0                    False                   False                   False   
1                    False                   False                   False   
2                    False                   False                   False   
3                    False                   False                   False   
4                    False                   False                   False   
5                    False                   False                   False   
6                    False                   False                   False   
7                    False                   False                   False   
8                    False                   False                   False   
9                    False                   False                   False   
10                   False                   False                   False   
11                   False       

In [28]:
d.dropna(inplace=True)
d.isnull().sum()

Temperatura Media (C)          0
Temperatura Minima (C)         0
Temperatura Maxima (C)         0
Precipitacao (mm)              0
Final de Semana                0
Consumo de cerveja (litros)    0
dtype: int64

In [42]:
d

Temperatura Media (C)  Temperatura Minima (C)  Temperatura Maxima (C)  \
0                    27.30                    23.9                    32.5   
1                    27.02                    24.5                    33.5   
2                    24.82                    22.4                    29.9   
3                    23.98                    21.5                    28.6   
4                    23.82                    21.0                    28.3   
5                    23.78                    20.1                    30.5   
6                    24.00                    19.5                    33.7   
7                    24.90                    19.5                    32.8   
8                    28.20                    21.9                    34.0   
9                    26.76                    22.1                    34.2   
10                   27.62                    22.2                    34.8   
11                   25.96                    21.4                    35.4   
12                   25.52                    21.2                    34.8   
13                   25.96                    21.3                    34.0   
14                   25.86                    21.5                    32.8   
15                   26.50                    22.3                    32.7   
16                   28.86                    22.0                    35.8   
17                   28.26                    23.4                    35.6   
18                   28.22                    22.7                    36.5   
19                   27.68                    23.3                    35.6   
20                   25.32                    22.7                    30.9   
21                   21.74                    19.2                    26.1   
22                   21.04                    18.5                    26.1   
23                   23.12                    19.0                    29.4   
24                   24.40                    18.1                    30.0   
25                   22.40                    18.9                    28.7   
26                   23.60                    20.5                    28.7   
27                   25.68                    20.1                    29.9   
28                   25.00                    21.5                    29.2   
29                   22.80                    20.9                    26.9   
..                     ...                     ...                     ...   
335                  22.10                    18.2                    29.4   
336                  22.44                    20.2                    26.1   
337                  22.76                    19.0                    29.1   
338                  24.80                    19.5                    30.6   
339                  23.12                    20.6                    28.0   
340                  20.04                    18.0                    23.9   
341                  21.70                    18.0                    28.0   
342                  23.96                    19.6                    27.9   
343                  24.00                    22.2                    27.7   
344                  24.04                    20.7                    30.3   
345                  23.92                    20.6                    30.8   
346                  24.54                    19.3                    31.0   
347                  26.28                    21.1                    32.5   
348                  25.66                    20.6                    32.8   
349                  22.04                    20.7                    24.8   
350                  23.32                    18.9                    28.7   
351                  26.42                    19.6                    33.5   
352                  23.74                    19.8                    31.3   
353                  22.84                    19.6                    29.0   
354                  23.12 

In [30]:
X= d.iloc[ : , :-1].values
X

array([[27.3 , 23.9 , 32.5 ,  0.  ,  0.  ],
       [27.02, 24.5 , 33.5 ,  0.  ,  0.  ],
       [24.82, 22.4 , 29.9 ,  0.  ,  1.  ],
       ...,
       [21.68, 20.3 , 24.1 , 10.3 ,  0.  ],
       [21.38, 19.3 , 22.4 ,  6.3 ,  0.  ],
       [24.76, 20.2 , 29.  ,  0.  ,  0.  ]])

In [33]:
from sklearn.model_selection import train_test_split
X_test, X_train = train_test_split(X,test_size=0.2)
X_train

array([[14.82, 12.1 , 18.1 ,  9.  ,  0.  ],
       [27.46, 22.1 , 32.4 ,  3.  ,  0.  ],
       [16.46, 13.  , 22.5 ,  0.2 ,  0.  ],
       [22.24, 19.3 , 29.3 ,  2.  ,  0.  ],
       [20.1 , 13.8 , 26.3 ,  0.  ,  1.  ],
       [25.24, 17.2 , 32.6 ,  0.  ,  0.  ],
       [17.54, 15.3 , 20.4 ,  0.  ,  0.  ],
       [27.02, 24.5 , 33.5 ,  0.  ,  0.  ],
       [18.64, 17.  , 22.9 ,  0.  ,  0.  ],
       [22.94, 19.7 , 27.1 ,  0.  ,  0.  ],
       [19.6 , 15.2 , 27.2 ,  0.  ,  0.  ],
       [19.92, 16.8 , 25.7 ,  0.  ,  1.  ],
       [17.76, 15.9 , 20.4 ,  0.  ,  0.  ],
       [22.22, 19.9 , 26.4 , 13.4 ,  0.  ],
       [16.76, 15.5 , 19.2 ,  0.1 ,  1.  ],
       [22.98, 18.3 , 29.8 ,  0.  ,  0.  ],
       [20.8 , 19.6 , 23.6 , 13.6 ,  0.  ],
       [18.6 , 17.1 , 21.3 ,  0.2 ,  1.  ],
       [26.16, 23.3 , 30.4 ,  0.  ,  0.  ],
       [16.84, 13.6 , 21.5 ,  0.  ,  0.  ],
       [17.02, 14.9 , 18.7 ,  4.5 ,  0.  ],
       [25.5 , 17.6 , 30.5 , 14.1 ,  0.  ],
       [23.28, 19.1 , 29.5 ,  0.

In [34]:
X_test

array([[21.28, 19.7 , 24.8 ,  0.  ,  0.  ],
       [22.12, 19.9 , 23.7 ,  3.2 ,  0.  ],
       [28.12, 18.9 , 35.8 ,  0.  ,  0.  ],
       ...,
       [28.3 , 20.5 , 35.3 ,  0.  ,  0.  ],
       [21.86, 19.5 , 25.6 ,  3.4 ,  0.  ],
       [23.24, 19.2 , 30.3 ,  0.  ,  0.  ]])

In [0]:
from sklearn.preprocessing import StandardScaler
standard_X = StandardScaler()

In [0]:
X_train = standard_X.fit_transform(X_train)
X_test = standard_X.fit_transform(X_test)

In [0]:
d.to_csv(r'/content/beerdataset.csv')
